[SERVICE]
    Flush        5
    Log_Level    info

[INPUT]
    Name         cpu
    Tag          vps.cpu

[OUTPUT]
    Name            opensearch
    Match           *
    Host            aventra-opensearch
    Port            9200
    Index           vps-system-logs
    tls             Off
    Suppress_Type_Name On
