apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:           # stringData = tulis plain text, K8s encode otomatis
  DB_PASSWORD: "airflow123"
  API_KEY: "aventra-secret-key"
  FERNET_KEY: "gXE_SB9-EG7x4a8S9Kkchh6DIEEmSPyynXR0nuLjuBU="